id: IC838438B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T18:40:03+00:00'
last_modified: '2022-06-08T02:30:24.874007+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20026
  title: རིན་གཏེར་སྨན་ཡིག་གཅེས་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A966:
      image_group_id: I1KG12929
      title: ''
      total_pages: 748
      order: 1
      base_file: A966.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
