id: P004639
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20026
  title: རིན་གཏེར་སྨན་ཡིག་གཅེས་བཏུས།
  author: ''
  volumes:
    fb5870ddcfe143669f911e5745e7cacb:
      image_group_id: I1KG12929
      title: ''
      volume_number: 1
      total_pages: 748
      base_file: v001.txt
